version: "3"
services:
  nginx:
    image: nginx:alpine
    volumes: 
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      nginx_net:
        ipv4_address: 172.16.238.10
    ports: 
      - "80:80"

  qbittorrent:
    build: ./qbittorrent
    volumes:
      - ./qbittorrent/config/qBittorrent:/root/.config/qBittorrent
      - ./qbittorrent/data/qBittorrent:/root/.local/share/data/qBittorrent
      - ./qbittorrent/downloads:/root/Downloads
      - ./rclone/rclone.conf:/root/.config/rclone/rclone.conf
    networks:
      nginx_net:
        ipv4_address: 172.16.238.11

networks: 
  nginx_net:
    ipam: 
      driver: default
      config: 
        - subnet: "172.16.238.0/24"